# Generated by Django 5.1.4 on 2025-01-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('quality', models.CharField(max_length=50)),
                ('weapon', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
